### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by LucasMW** [red/wallet#26]
Current version does not compile on Mac OS

red -r -t macOS wallet.red

-=== Red Compiler 0.6.3 ===- 

Compiling ../Cloned_From_Github/wallet/wallet.red ...
...compilation time : 2237 ms

Target: macOS 

Compiling to native code...
*** Compilation Error: type casting from function! to pointer! is not allowed 
*** in file: .../Cloned_From_Github/wallet/libs/HID/macOS.reds 
*** in function: exec/hid/open_path
*** at line: 950 
*** near: [
    IOHIDDeviceRegisterRemovalCallback dev/device_handle 
    as pointer! [integer!] :hid_device_removal_callback 
    as pointer!
]

**Comment by LucasMW** [comment]
Windows compiles, however. I still can't run on Mac OS, though.

$red -r -t Windows wallet.red

-=== Red Compiler 0.6.3 ===- 

Compiling .../Cloned_From_Github/wallet/wallet.red ...
...compilation time : 2516 ms

Target: Windows 

Compiling to native code...
...compilation time : 68209 ms
...linking time     : 598 ms
...output file size : 1014784 bytes
...output file      : .../Cloned_From_Github/wallet/wallet.exe 


$ wine wallet.exe 
0009:fixme:dwmapi:DwmIsCompositionEnabled 0x32feb0

*** Runtime Error 0009:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x4199e3
$ du -sh wallet.exe
992K	wallet.exe

**Comment by qtxie** [comment]
The compilation error has been fixed in the latest red compiler.
