### ISSUE TITLE
Fetch balance: Timeout. Please try "Reload" again

### ISSUE THREAD

**Issue by AugustoResende** [red/wallet#64]
Fetch balance: Timeout. Please try "Reload" again

**Comment by 9214** [comment]
@AugustoResende can you be a bit more specific: is it BTC or ETH, which OS are you on, and are you using the latest Red build?

**Comment by AugustoResende** [comment]
ETH, latest public release, Windows, looks https://eth.red-lang.org/mainnet is down

**Comment by AugustoResende** [comment]
Fixed
