### ISSUE TITLE
Compilation Error: undefined word to-json

### ISSUE THREAD

**Issue by AugustoResende** [red/wallet#65]
```
*** Compilation Error: undefined word to-json
*** in file: C:\Users\augus\Documents\Projects\wallet\wallet.red
*** near: [to-json body
    headers/cookie: cookie data
    res: attempt [
        write network compose/only [
            POST
            (headers)
            (to-binary data)
        ]
    ]
]
```

**Comment by 9214** [comment]
Please follow the [instructions](https://github.com/red/wallet#quick-and-easy-way) and use the [latest automated build](https://static.red-lang.org/dl/auto/win/red-latest.exe) when compiling the wallet from sources.

**Comment by AugustoResende** [comment]
@9214 I've used LATEST AUTOMATED BUILD, exactly following the instructions

**Comment by AugustoResende** [comment]
red-06may20-6b1a117cd.exe

**Comment by qtxie** [comment]
Should be fixed with latest red and wallet code.
