### ISSUE TITLE
How to add a new ERC-20 token?

### ISSUE THREAD

**Issue by AugustoResende** [red/wallet#67]
What is the SIGNATURE in tokens-list.red 

I want to add this brazilian token
https://etherscan.io/token/0xa6fa6531acdf1f9f96eddd66a0f9481e35c2e42a

**Comment by qtxie** [comment]
Are you using Ledger key? Is this token supported by the hardware key?

**Comment by AugustoResende** [comment]
@qtxie Ledger supports EVERY ERC-20 TOKEN

**Comment by qtxie** [comment]
@AugustoResende Of course you can send ANY ERC-20 token with Ledger, that doesn't mean ledger can recognize it. Here is the list of tokens supported by Ledger: https://www.ledger.com/supported-crypto-assets

**Comment by AugustoResende** [comment]
No you are wrong, Ledger (Key) supports every ERC20 token using other
interfaces than Ledger Live

This list is for Ledger Live only.

I'm able tô use cryptobrl on Ledger using MyEtherWallet

Em qui, 7 de mai de 2020 22:43, Qingtian <notifications@github.com>
escreveu:

**Comment by qtxie** [comment]
@AugustoResende I know every ERC20 token can be sent by Ledger. It does not mean Ledger knows the token. Does the token name "cryptobrl" show on your Ledger key when doing transactions using MyEtherWallet?

Only after Ledger SUPPORT `RED` token, the RED token name show on the ledger key.
![image](https://user-images.githubusercontent.com/1673525/81369424-f5635780-9124-11ea-9204-863916b0f6a4.png)

**Comment by AugustoResende** [comment]
Yes, but i only want to add on the Red Wallet, not in Ledger internal software

**Comment by qtxie** [comment]
For security concern, current version of the wallet don't allow the user to add external tokens. The file tokens-list.red was generated by a script. 

You can try to use [this script](https://github.com/red/wallet/blob/master/utils/extract-tokens.red) to generate a new tokens-list.red to see if CBRL is supported.
